baseURL = 'https://example.org/'
languageCode = 'en-gb'
defaultContentLanguage = 'en-gb'
title = 'Galactic IT'
theme = "lentil"
copyright = '© KeBab Technologies Ltd'

[module]
  [[module.mounts]]
    source = 'node_modules/lucide-static'
    target = 'assets'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'


[markup.goldmark.parser.attribute]
  block = true
  title = true
[markup.goldmark.renderer]
  unsafe = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = "Case Studies"
    pageRef = '/case_studies'
    weight = 30
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 40
  [[menus.main]]
    name = "About Us"
    weight = 50
  [[menus.main]]
    name = "Team"
    parent = 'About Us'
    pageRef = '/team'
    weight = 10

  
  [[menus.footer]]
    name = 'Terms'
    pageRef = '/terms'
    weight = 10
  [[menus.footer]]
    name = 'Privacy'
    pageRef = '/privacy'
    weight = 20