baseURL = 'https://example.org/'
languageCode = 'en-gb'
defaultContentLanguage = 'en-gb'
title = 'Galactic IT'
theme = "lentil"
copyright = '© KeBab Technologies Ltd'

# Custom Variables
[params]
  defaultColor = "green"

[module]
  [[module.mounts]]
    source = 'node_modules/lucide-static'
    target = 'assets'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

[build]
  [build.buildStats]
   enable = true

[markup.goldmark.parser.attribute]
  block = true
  title = true
[markup.goldmark.renderer]
  unsafe = true 

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Insights'
    pageRef = '/insights'
    weight = 20
  [[menus.main]]
    name = "Case Studies"
    pageRef = '/case_studies'
    weight = 30
  [[menus.main]]
    name = "About Us"
    weight = 50
  [[menus.main]]
    name = "Team"
    parent = 'About Us'
    pageRef = '/team'
    weight = 10


  [[menus.footer]]
    name = 'Terms'
    pageRef = '/terms'
    weight = 10
  [[menus.footer]]
    name = 'Privacy'
    pageRef = '/privacy'
    weight = 20
